apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: dgsdev/api-produto:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin  

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec: 
  selector:
    app: api
  ports: 
    - port: 80
      targetPort: 5000 
      nodePort: 30000 
  type: LoadBalancer      

